language: python
python:
  - 3.6

sudo: false

env:
  global:
    - MASTER_BRANCH=master

env:
  - TEST_DIR='tests'

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --quiet --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib ipython;
  - conda install --quiet --yes -c conda-forge discretize properties vectormath utm
  - pip install -r requirements_dev.txt
  - python setup.py install
  - export MPLBACKEND="agg"

# Run test
script:
  - nosetests $TEST_DIR --with-cov --cov geoana -v -s;

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # early exit if not on a deplotment branch
  - if ! [ "$TRAVIS_BRANCH" = "$MASTER_BRANCH" -o "$TRAVIS_TAG" = "true" ]; then
      echo "Not deploying (because this is not a deployment branch)" ;
      exit 0 ;
    fi
  - if ! [ $TRAVIS_PULL_REQUEST = "false" ] ; then
      echo "Not deploying (because this is a pull request)" ;
      exit 0 ;
    fi
  - echo "Deploying"

  # unpack credentials
  - openssl aes-256-cbc -K $encrypted_e1a1deb7b9e1_key -iv $encrypted_e1a1deb7b9e1_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xvzf credentials.tar.gz

  # deploy to pypi
  - mv credentials/.pypirc ~/.pypirc ;
  - python setup.py sdist ;
  - twine upload dist/* --skip-existing ;
