language: python
python:
  - 3.4
  - 2.7

sudo: false

env:
  - TEST_DIR='tests'

install:
  - pip install --upgrade pip;
  - pip install -r requirements.txt
  - git clone https://github.com/3ptscience/vectormath;
  - export PATH=$PWD/vectormath:$PATH
  - pip install properties

# Run test
script:
  - nosetests $TEST_DIR
