language: python
python:
  - 3.6
  - 2.7

sudo: false

env:
  - TEST_DIR='tests'

install:
  - pip install --upgrade pip;
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - git clone https://github.com/3ptscience/vectormath;
  - export PYTHONPATH=$PWD/geoana:$PWD/vectormath:$PYTHONPATH

# Run test
script:
  - nosetests $TEST_DIR

after_success:
  - bash <(curl -s https://codecov.io/bash)
