name: TestingWithConda

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        update-conda: true
        activate-environment: geoana-test
        channels: conda-forge
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      shell: bash
      run: |
        conda info
        conda list
        conda config --show
        conda install --quiet --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib ipython;
        conda install --quiet --yes discretize properties vectormath utm pytest pytest-cov
        pip install -r requirements_dev.txt

    - name: Install Our Package
      shell: bash
      run: |
        export BUILD_GEOANA_EXT=1
        pip install -e .
        conda list
    - name: Run Tests
      shell: bash
      run: |
        source activate geoana-test
        pytest --cov=./ --cov-report=xml --cov=geoana -s -v -W ignore::DeprecationWarning

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
